#!/usr/bin/env bash

export CONTECO_LABEL="Conteco registry base"
export CONTECO_DESCRIPTION="The Docker registry base image."

export CONTECO_TYPE="registry"
export CONTECO_NAME="base"
export CONTECO_TAG="2"

export CONTECO_BASE="external.registry:2"
export CONTECO_BUILD="image-base"
