#!/usr/bin/env bash

export CONTECO_LABEL="registry.base - ContEco"
export CONTECO_DESCRIPTION="Docker Registry Base, useding default configuration."

export CONTECO_TYPE="registry"
export CONTECO_NAME="base"
export CONTECO_TAG="2"

export CONTECO_BASE="external.registry:2"
export CONTECO_BUILD="image-base"
