---
version: '3'
services:

# START SERVICE registry.base
  registry:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.registry.base:2
    environment: []
    command: []
    volumes: [${CONTECO_STACKPREFIX}_registry_volume:/var/lib/registry]
    ports: [${CONTECO_DC_REGISTRY_PORTS}]
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${CONTECO_DC_REGISTRY_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_REGISTRY_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_REGISTRY_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_REGISTRY_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${CONTECO_DC_REGISTRY_DEPLOY_PLACEMENT_CONSTRAINTS}]
      ${CONTECO_DC_BASH_DEPLOY_EXTENSIONS}
    ${CONTECO_DC_BASH_SERVICE_EXTENSIONS}
# END SERVICE registry.base

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${CONTECO_STACKPREFIX}_registry_volume: { external: true }}
${CONTECO_DC_BASH_GLOBAL_EXTENSIONS}
