---
version: '3'
services:

# START SERVICE registry.base
  registry:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.registry.base:2
    environment: []
    command: []
    volumes: [${CONTECO_DC_REGISTRY_VOLUME_NAME}:/var/lib/registry]
    ports: [${CONTECO_DC_REGISTRY_PORTS}]
    networks: [${CONTECO_DC_REGISTRY_NETWORKS}]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${CONTECO_DC_REGISTRY_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_REGISTRY_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_REGISTRY_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_REGISTRY_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [${CONTECO_DC_REGISTRY_DEPLOY_LABELS}]
# END SERVICE registry.base

volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
networks: {${CONTECO_DC_GLOBAL_NETWORKS}}
